### ISSUE TITLE
URL with GloVe dataset not working stanfordnlp/GloVe

### ISSUE THREAD

**Issue by mukesh-2538** [stanfordnlp/GloVe#180]
Not able to download the pretrained Glove embeddings.

**Comment by Catonzio** [comment]
The problem is that the link is on HTTP, but the real download link is on HTTPS.
A little trick is to copy the link and paste it in the browser, changing http:// to https://

**Comment by AngledLuffa** [comment]
*facepalm*

TY for catching that.  It should now be fixed.

**Comment by PosoSAgapo** [comment]
Seems the downloading url is not working again even change the http to https does not solve the problem. Any way to fix this ?@AngledLuffa

**Comment by AngledLuffa** [comment]
Which link isn't working?  I'm able to download things.

**Comment by AngledLuffa** [comment]
Are you using Chrome?  I've sometimes had issues where Chrome doesn't want
to follow a link to something "unsafe" like a zip file.

**Comment by PosoSAgapo** [comment]
> Are you using Chrome? I've sometimes had issues where Chrome doesn't want to follow a link to something "unsafe" like a zip file.

Yep, I am using Chrome.,but I have solved it  using wget command, it could directly download the glove embedding ;)
